package com.yang.mysql.domain;

import java.time.LocalDateTime;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private String saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.store_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_seq
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private String productSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sku_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.spu_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private String spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.valid
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_id
     *
     * @return the value of product.sale_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_id
     *
     * @param saleId the value for product.sale_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.store_id
     *
     * @return the value of product.store_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.store_id
     *
     * @param storeId the value for product.store_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_seq
     *
     * @return the value of product.product_seq
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public String getProductSeq() {
        return productSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_seq
     *
     * @param productSeq the value for product.product_seq
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setProductSeq(String productSeq) {
        this.productSeq = productSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sku_id
     *
     * @return the value of product.sku_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sku_id
     *
     * @param skuId the value for product.sku_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.spu_id
     *
     * @return the value of product.spu_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public String getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.spu_id
     *
     * @param spuId the value for product.spu_id
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setSpuId(String spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.valid
     *
     * @return the value of product.valid
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.valid
     *
     * @param valid the value for product.valid
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSaleId() == null ? other.getSaleId() == null : this.getSaleId().equals(other.getSaleId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getProductSeq() == null ? other.getProductSeq() == null : this.getProductSeq().equals(other.getProductSeq()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getSpuId() == null ? other.getSpuId() == null : this.getSpuId().equals(other.getSpuId()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSaleId() == null) ? 0 : getSaleId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getProductSeq() == null) ? 0 : getProductSeq().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getSpuId() == null) ? 0 : getSpuId().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Oct 27 09:49:36 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", saleId=").append(saleId);
        sb.append(", storeId=").append(storeId);
        sb.append(", productSeq=").append(productSeq);
        sb.append(", skuId=").append(skuId);
        sb.append(", spuId=").append(spuId);
        sb.append(", valid=").append(valid);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}